
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buntudelice-api
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - DB_HOST=host.docker.internal
      - DB_PORT=55509
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - JWT_SECRET=${JWT_SECRET:-buntudelice_secret_key}
      - PORT=4000
      - CORS_ORIGIN=http://localhost:9595
    restart: unless-stopped
    networks:
      - buntudelice-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

# Database is now handled by Supabase PostgreSQL
# No local database service needed

networks:
  buntudelice-network:
    driver: bridge
