
version: '3.8'

services:
  api:
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs:ro
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.buntudelice.com`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"

  db:
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    volumes:
      - buntudelice-db-data:/var/lib/mysql
      - ./db/backup:/backup

  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
    networks:
      - buntudelice-network
