<?php

return [
    'food_delivery' => [
        'business_statuses' => [
            'basket',
            'pending_payment',
            'pending_restaurant_acceptance',
            'accepted_awaiting_payment',
            'confirmed',
            'accepted',
            'in_kitchen',
            'ready_for_pickup',
            'dispatching',
            'driver_assigned',
            'driver_arrived_at_restaurant',
            'picked_up',
            'out_for_delivery',
            'delivery_attempt_failed',
            'delivered',
            'partially_delivered',
            'cancelled',
            'refunded',
            'incident_open',
            'closed',
        ],
        'technical_statuses' => [
            'payment_pending_confirmation',
            'payment_authorized',
            'payment_captured',
            'payment_failed',
            'dispatch_retry',
            'restaurant_timeout',
            'driver_timeout',
            'proof_pending',
            'fraud_hold',
            'payment_disputed',
        ],
        'transitions' => [
            'basket' => ['pending_payment'],
            'pending_payment' => ['pending_restaurant_acceptance', 'cancelled'],
            'pending_restaurant_acceptance' => ['accepted_awaiting_payment', 'confirmed', 'cancelled'],
            'accepted_awaiting_payment' => ['confirmed', 'cancelled'],
            'confirmed' => ['in_kitchen', 'cancelled'],
            'accepted' => ['in_kitchen', 'ready_for_pickup', 'driver_assigned', 'cancelled'],
            'in_kitchen' => ['ready_for_pickup', 'incident_open', 'cancelled'],
            'ready_for_pickup' => ['dispatching', 'driver_assigned', 'picked_up', 'cancelled'],
            'dispatching' => ['driver_assigned', 'picked_up', 'incident_open', 'cancelled'],
            'driver_assigned' => ['driver_arrived_at_restaurant', 'picked_up', 'dispatching', 'cancelled'],
            'driver_arrived_at_restaurant' => ['picked_up', 'dispatching', 'cancelled'],
            'picked_up' => ['out_for_delivery', 'incident_open'],
            'out_for_delivery' => ['delivered', 'delivery_attempt_failed', 'incident_open'],
            'delivery_attempt_failed' => ['out_for_delivery', 'incident_open', 'cancelled'],
            'delivered' => ['closed'],
            'partially_delivered' => ['incident_open', 'closed'],
            'refunded' => ['closed'],
            'incident_open' => ['closed', 'cancelled', 'refunded'],
            'cancelled' => ['closed'],
            'closed' => [],
        ],
        'legacy_mapping' => [
            'pending' => 'pending_restaurant_acceptance',
            'prepairing' => 'in_kitchen',
            'assign' => 'dispatching',
            'completed' => 'delivered',
            'cancelled' => 'cancelled',
        ],
    ],
    'food_pickup' => [
        'business_statuses' => [
            'basket',
            'pending_payment',
            'pending_restaurant_acceptance',
            'accepted_awaiting_payment',
            'confirmed',
            'accepted',
            'in_kitchen',
            'ready_for_pickup',
            'customer_arrived',
            'picked_up_by_customer',
            'no_show',
            'cancelled',
            'closed',
        ],
        'transitions' => [
            'basket' => ['pending_payment'],
            'pending_payment' => ['pending_restaurant_acceptance', 'cancelled'],
            'pending_restaurant_acceptance' => ['accepted_awaiting_payment', 'confirmed', 'cancelled'],
            'accepted_awaiting_payment' => ['confirmed', 'cancelled'],
            'confirmed' => ['in_kitchen', 'cancelled'],
            'accepted' => ['in_kitchen', 'cancelled'],
            'in_kitchen' => ['ready_for_pickup', 'cancelled'],
            'ready_for_pickup' => ['customer_arrived', 'no_show', 'cancelled'],
            'customer_arrived' => ['picked_up_by_customer'],
            'picked_up_by_customer' => ['closed'],
            'no_show' => ['ready_for_pickup', 'cancelled', 'closed'],
            'cancelled' => ['closed'],
            'closed' => [],
        ],
    ],
    'parcel' => [
        'enum_source' => 'App\\Domain\\Colis\\Enums\\ShipmentStatus',
        'extensions' => [
            'delivery_attempt_failed',
            'return_scheduled',
            'cod_reconciled',
        ],
    ],
    'transport' => [
        'enum_source' => 'App\\Domain\\Transport\\Enums\\TransportStatus',
        'extensions' => [
            'rider_no_show',
            'driver_no_show',
            'surge_pending_confirmation',
            'dispute_open',
        ],
    ],
];
