<?php

return [
    'directory' => [
        [
            'kind' => 'district',
            'popularity' => 95,
            'label' => 'Ouenzé, Brazzaville, Congo',
            'address_line' => 'Ouenzé',
            'lat' => -4.243800,
            'lng' => 15.281900,
            'aliases' => [
                'ouenze',
                'ouenze arrondissement 5',
                'quartier ouenze',
            ],
            'components' => [
                'house_number' => null,
                'road' => null,
                'neighbourhood' => null,
                'suburb' => 'Ouenzé',
                'city_district' => 'Ouenzé',
                'city' => 'Brazzaville',
                'state' => 'Brazzaville',
                'country' => 'Congo',
            ],
            'precision' => [
                'source' => 'kende_local',
                'level' => 'district',
                'house_number_confirmed' => false,
                'road_confirmed' => false,
                'district_confirmed' => true,
            ],
        ],
        [
            'kind' => 'road',
            'popularity' => 82,
            'label' => 'Rue Makoko, Ouenzé, Brazzaville, Congo',
            'address_line' => 'Rue Makoko',
            'lat' => -4.243711,
            'lng' => 15.282023,
            'aliases' => [
                'rue makoko',
                'makoko',
                'ouenze makoko',
                'rue makoko ouenze',
            ],
            'components' => [
                'house_number' => null,
                'road' => 'Rue Makoko',
                'neighbourhood' => 'Ouenzé-Konda',
                'suburb' => 'Ouenzé',
                'city_district' => 'Ouenzé',
                'city' => 'Brazzaville',
                'state' => 'Brazzaville',
                'country' => 'Congo',
            ],
            'precision' => [
                'source' => 'kende_local',
                'level' => 'street',
                'house_number_confirmed' => false,
                'road_confirmed' => true,
                'district_confirmed' => true,
            ],
        ],
        [
            'kind' => 'district',
            'popularity' => 92,
            'label' => 'Poto-Poto, Brazzaville, Congo',
            'address_line' => 'Poto-Poto',
            'lat' => -4.269500,
            'lng' => 15.270800,
            'aliases' => [
                'poto poto',
                'quartier poto poto',
            ],
            'components' => [
                'house_number' => null,
                'road' => null,
                'neighbourhood' => null,
                'suburb' => 'Poto-Poto',
                'city_district' => 'Poto-Poto',
                'city' => 'Brazzaville',
                'state' => 'Brazzaville',
                'country' => 'Congo',
            ],
            'precision' => [
                'source' => 'kende_local',
                'level' => 'district',
                'house_number_confirmed' => false,
                'road_confirmed' => false,
                'district_confirmed' => true,
            ],
        ],
        [
            'kind' => 'road',
            'popularity' => 80,
            'label' => 'Rue Béhangle, Poto-Poto, Brazzaville, Congo',
            'address_line' => 'Rue Béhangle',
            'lat' => -4.269441,
            'lng' => 15.271226,
            'aliases' => [
                'rue behangle',
                'behangle',
                'poto poto behangle',
                'rue behangle poto poto',
            ],
            'components' => [
                'house_number' => null,
                'road' => 'Rue Béhangle',
                'neighbourhood' => null,
                'suburb' => 'Poto-Poto',
                'city_district' => 'Poto-Poto',
                'city' => 'Brazzaville',
                'state' => 'Brazzaville',
                'country' => 'Congo',
            ],
            'precision' => [
                'source' => 'kende_local',
                'level' => 'street',
                'house_number_confirmed' => false,
                'road_confirmed' => true,
                'district_confirmed' => true,
            ],
        ],
        [
            'kind' => 'district',
            'popularity' => 94,
            'label' => 'Moungali, Brazzaville, Congo',
            'address_line' => 'Moungali',
            'lat' => -4.257800,
            'lng' => 15.259800,
            'aliases' => [
                'moungali',
                'quartier moungali',
                'arrondissement moungali',
            ],
            'components' => [
                'house_number' => null,
                'road' => null,
                'neighbourhood' => null,
                'suburb' => 'Moungali',
                'city_district' => 'Moungali',
                'city' => 'Brazzaville',
                'state' => 'Brazzaville',
                'country' => 'Congo',
            ],
            'precision' => [
                'source' => 'kende_local',
                'level' => 'district',
                'house_number_confirmed' => false,
                'road_confirmed' => false,
                'district_confirmed' => true,
            ],
        ],
        [
            'kind' => 'road',
            'popularity' => 88,
            'label' => 'Avenue des Trois Martyrs, Moungali, Brazzaville, Congo',
            'address_line' => 'Avenue des Trois Martyrs',
            'lat' => -4.263400,
            'lng' => 15.242900,
            'aliases' => [
                'avenue des trois martyrs',
                'trois martyrs',
                'av trois martyrs',
            ],
            'components' => [
                'house_number' => null,
                'road' => 'Avenue des Trois Martyrs',
                'neighbourhood' => 'Batignolles',
                'suburb' => 'Moungali',
                'city_district' => 'Moungali',
                'city' => 'Brazzaville',
                'state' => 'Brazzaville',
                'country' => 'Congo',
            ],
            'precision' => [
                'source' => 'kende_local',
                'level' => 'street',
                'house_number_confirmed' => false,
                'road_confirmed' => true,
                'district_confirmed' => true,
            ],
        ],
        [
            'kind' => 'landmark',
            'popularity' => 97,
            'label' => 'Stade Massamba-Débat, Centre-ville, Brazzaville, Congo',
            'address_line' => 'Stade Massamba-Débat',
            'lat' => -4.263000,
            'lng' => 15.274600,
            'aliases' => [
                'massamba debat',
                'stade massamba debat',
                'stade massamba',
            ],
            'components' => [
                'house_number' => null,
                'road' => null,
                'neighbourhood' => null,
                'suburb' => 'Centre-ville',
                'city_district' => 'Centre-ville',
                'city' => 'Brazzaville',
                'state' => 'Brazzaville',
                'country' => 'Congo',
            ],
            'precision' => [
                'source' => 'kende_local',
                'level' => 'district',
                'house_number_confirmed' => false,
                'road_confirmed' => false,
                'district_confirmed' => true,
            ],
        ],
        [
            'kind' => 'road',
            'popularity' => 90,
            'label' => 'Boulevard Denis Sassou Nguesso, Centre-ville, Brazzaville, Congo',
            'address_line' => 'Boulevard Denis Sassou Nguesso',
            'lat' => -4.263900,
            'lng' => 15.284500,
            'aliases' => [
                'boulevard denis sassou nguesso',
                'bd denis sassou nguesso',
                'sassou nguesso',
            ],
            'components' => [
                'house_number' => null,
                'road' => 'Boulevard Denis Sassou Nguesso',
                'neighbourhood' => null,
                'suburb' => 'Centre-ville',
                'city_district' => 'Centre-ville',
                'city' => 'Brazzaville',
                'state' => 'Brazzaville',
                'country' => 'Congo',
            ],
            'precision' => [
                'source' => 'kende_local',
                'level' => 'street',
                'house_number_confirmed' => false,
                'road_confirmed' => true,
                'district_confirmed' => true,
            ],
        ],
        [
            'kind' => 'district',
            'popularity' => 91,
            'label' => 'Bacongo, Brazzaville, Congo',
            'address_line' => 'Bacongo',
            'lat' => -4.282700,
            'lng' => 15.286200,
            'aliases' => [
                'bacongo',
                'quartier bacongo',
            ],
            'components' => [
                'house_number' => null,
                'road' => null,
                'neighbourhood' => null,
                'suburb' => 'Bacongo',
                'city_district' => 'Bacongo',
                'city' => 'Brazzaville',
                'state' => 'Brazzaville',
                'country' => 'Congo',
            ],
            'precision' => [
                'source' => 'kende_local',
                'level' => 'district',
                'house_number_confirmed' => false,
                'road_confirmed' => false,
                'district_confirmed' => true,
            ],
        ],
        [
            'kind' => 'road',
            'popularity' => 78,
            'label' => 'Corniche, Bacongo, Brazzaville, Congo',
            'address_line' => 'Corniche',
            'lat' => -4.282800,
            'lng' => 15.286000,
            'aliases' => [
                'corniche',
                'corniche bacongo',
            ],
            'components' => [
                'house_number' => null,
                'road' => 'Corniche',
                'neighbourhood' => null,
                'suburb' => 'Bacongo',
                'city_district' => 'Bacongo',
                'city' => 'Brazzaville',
                'state' => 'Brazzaville',
                'country' => 'Congo',
            ],
            'precision' => [
                'source' => 'kende_local',
                'level' => 'street',
                'house_number_confirmed' => false,
                'road_confirmed' => true,
                'district_confirmed' => true,
            ],
        ],
    ],
];
