// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frwviexczcdkpusrhjdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyd3ZpZXhjemNka3B1c3JoamRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMTU4MzEsImV4cCI6MjA1MTY5MTgzMX0.5345HC0DtubYgEttdirmp3Od8BP1ea1TQv5EaUG7Ujc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);